spring:
  application:
    name: core-api

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: ${ELA_PASSWORD}

  rabbitmq:
    host: 43.202.250.117
    port: 5672
    username: ps
    password: ${DB_MQ_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.202.250.117:3306/be6_aa_prod?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ps
    password: ${DB_MQ_PASSWORD}
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 3
    max-total: 5
    max-idle: 3
    min-idle: 1

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

api:
  gateway:
    host: buzz-book.shop
    port: 8000

eureka:
  instance:
    instance-id: core-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
