spring:
  application:
    name: core-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_aa_coupon_prod?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: be6_aa
    password: 6@H(77fpCZDiC6!!
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 20
    max-total: 200
    max-idle: 200
    min-idle: 20

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

api:
  gateway:
    host: buzz-book.store
    port: 8080

eureka:
  instance:
    instance-id: core-api
    hostname: eureka-server
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka

nhncloud:
  keymanager:
    appkey: 2SxwmBzUfnqJaA2A
    mysql:
      url: c7d282283c5c4ddcae6072324adfe3c3
      username: 0f85ac52219545d382eab76db989e848
      password: 54e01f8caa504a6ca5e69d30e66bf348
  image:
    appkey: vyiy4M85i8mJ5mgP
    secretkey: fBlt6m4cSRJs07X05mhPBfmofWoBlcSU


